### ISSUE TITLE
parse output's an array when there is only a single Json Object

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/parse#13]
Given the following rule;

```
---
name: wrk2
path: "wrk2-(?<runtimeName>[^\\./]+)-jvm-(?<txRate>[^\\./]+).log"
nest: "wrk2.${{runtimeName}}.${{txRate}}"
asText: 
  - name: centile50
    pattern: "50.000%\\s*(?<centile50:String>\\d+\\.\\d+m?)s"
    eat: Line
  - name: centile99999
    pattern: "99.999%\\s*(?<centile99999:String>\\d+\\.\\d+m?)s"
    eat: Line
  - name: reqSec
    pattern: "^Requests/sec:\\s*(?<reqSec>\\d+\\.\\d+)"
    eat: Line
---
```

And file `wrk2-quarkus-jvm-2000.log` with contents;

```
Running 30s test @ http://localhost:8080/api
  16 threads and 400 connections
...
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.04ms
 75.000%    1.32ms
 90.000%    1.66ms
 99.000%    2.17ms
 99.900%    3.07ms
 99.990%    5.57ms
 99.999%   13.47ms
100.000%   13.47ms
...
```
The output Json nested under `wrk2.quarkus.2000` is a Json Array with a single object;

```
{
  "wrk2": {
    "quarkus": {
      "2000": [ 
        {
          "centile50": "9.00",
          "centile99999": "15.34",
          "reqSec": 8595.75
        }
      ]
    }
  }
}
```
Is there currently a way of outputting this as a Json Object, such that the output is;

```
{
  "wrk2": {
    "quarkus": {
      "2000": {
        "centile50": "9.00",
        "centile99999": "15.34",
        "reqSec": 8595.75
      }
    }
  }
}
```
